command: ['node', 'api/src/server.js']

oauth:
  scopes:
    - sql
    - jobs

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: 'DATABRICKS_CATALOG'
    value: 'wizz-test'
  - name: 'DATABRICKS_SCHEMA'
    value: 'test_schema'
