command: ['node', 'api/src/server.js']

oauth:
  scopes:
    - sql
    - all-apis

resources:
  - name: trigger-job
    job:
      id: "538667917154866"
      permission: CAN_MANAGE_RUN

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: 'DATABRICKS_CATALOG'
    value: 'wizz-test'
  - name: 'DATABRICKS_SCHEMA'
    value: 'test_schema'
